spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC
    username: root
    password: dkssud3857!
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

itemImgLocation: /Users/dohyunghong/shop/item
uploadPath: file:///Users/dohyunhong/shop/




logging:
  level:
    org.hibernate.type.descriptor.sql: trace
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
   # org.springframework: debug
   # org.springframework.web: debug
